sudo: false

language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

install: mvn -B install -U -DskipTests=true

script: mvn -B verify -U -Dmaven.javadoc.skip=true

cache:
  directories:
  - $HOME/.m2

branches:
  only:
    - travis-ci